require 'active_model'
require 'oauth'
require 'rspec'
require 'faraday'
require 'json'
require 'webmock/rspec'
require 'rake'
require 'rspec'
require 'shoulda-matchers'
require 'pry'

require 'launchy'
require './env'
require 'vcr'
require 'fakeweb'

require 'user'
